apiVersion: v1
kind: Service
metadata:
  namespace: zodiac
  name: hivezodiac
  labels:
    app: hivezodiac
spec:
  type: NodePort
  ports:
    - name: http
      port: {{.Values.hivezodiac.httpPort}}
      targetPort: {{.Values.hivezodiac.httpPort}}
      protocol: TCP
    - name: mqtt
      port: {{.Values.hivezodiac.mqttPort}}
      targetPort: {{.Values.hivezodiac.mqttPort}}
      nodePort: {{.Values.hivezodiac.mqttNodePort}}
      protocol: TCP
    - name: websocket
      port: {{.Values.hivezodiac.websocketPort}}
      targetPort: {{.Values.hivezodiac.websocketPort}}
  selector:
    app: hivezodiac
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zodiac
  name: hivezodiac
  labels:
    app: hivezodiac
  annotations:
    keel.sh/policy: minor
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hivezodiac
  template:
    metadata:
      labels:
        app: hivezodiac
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: hivezodiac
          image: "{{ .Values.meta.imageUrl }}/hivezodiac:0.1.0-cicd"
          imagePullPolicy: Always
          ports:
            - containerPort: {{.Values.hivezodiac.httpPort}}
            - containerPort: {{.Values.hivezodiac.mqttPort}}
            - containerPort: {{.Values.hivezodiac.websocketPort}}
          env:
          resources: {}
          volumeMounts:
      volumes:
