apiVersion: v1
kind: ServiceAccount
metadata:
  name: log-collector-sa
  namespace: zodiac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: log-collector-reader
  namespace: zodiac
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: log-collector-reader-binding
  namespace: zodiac
subjects:
  - kind: ServiceAccount
    name: log-collector-sa
    namespace: zodiac
roleRef:
  kind: Role
  name: log-collector-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: log-collector-service
  namespace: zodiac
spec:
  type: NodePort
  selector:
    app: log-collector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-collector
  namespace: zodiac
  labels:
    app: log-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-collector
  template:
    metadata:
      labels:
        app: log-collector
    spec:
      serviceAccountName: log-collector-sa
      imagePullSecrets:
        - name: regcred
      containers:
        # --- CONTAINER 1: The Collector ---
        - name: log-collector
          image: "{{ .Values.meta.imageUrl }}/log-collector:0.1.0-cicd"
          imagePullPolicy: Always
          env:
            - name: KUBE_POD
              value: {{.Values.logCollector.kubePod}}
            - name: KUBE_NAMESPACE
              value: {{.Values.logCollector.kubeNamespace}}
            - name: STORAGE_FILE
              value: {{.Values.logCollector.storageFile}}
            - name: HTML_FILE
              value: {{.Values.logCollector.htmlFile}}
          volumeMounts:
            - name: logs-volume
              mountPath: /shared

        # --- CONTAINER 2: The HTTP Server (Sidecar) ---
        - name: log-server
          image: python:3.9-slim
          command: ["python3", "-c"]
          args:
            - |
              import http.server
              import socketserver
              import os

              # 1. Go to the logs folder
              os.chdir('/shared')

              # 2. Configure how files are handled
              handler = http.server.SimpleHTTPRequestHandler
              handler.extensions_map.update({
                  '.jsonl': 'text/plain', # Show raw logs as text
                  '.html': 'text/html',   # Show dashboard as a webpage
              })

              # 3. Start the server
              with socketserver.TCPServer(("", 8080), handler) as httpd:
                  print("Serving Dashboard at port 8080...")
                  httpd.serve_forever()
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: logs-volume
              mountPath: /shared
              readOnly: true

      volumes:
        - name: logs-volume
          emptyDir: {}
