apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zodiac
  name: new-agent
  labels:
    app: new-agent
  annotations:
    keel.sh/policy: minor
    keel.sh/trigger: poll

spec:
  replicas: 1
  selector:
    matchLabels:
      app: new-agent
  template:
    metadata:
      labels:
        app: new-agent
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: new-agent
          image: "{{ .Values.meta.imageUrl }}/new-agent:0.5.0-cicd"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.agent.port }}
          env:
            - name: MCP_URL
              value: "{{.Values.orionUi.chatApiBase}}{{.Values.orionUi.chatApiPath}}"
            - name: STREAM_MANAGER_URL
              value: "http://stream-manager:{{ .Values.streamManager.port }}"
            - name: MCP_REQUEST_TIMEOUT_SECONDS
              value: "{{ .Values.agent.mcpRequestTimeoutSeconds }}"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "{{.Values.mcp.env.otel_exporter_endpoint}}"
            - name: OTEL_SERVICE_NAME
              value: "agent-api"
            - name: OTEL_SERVICE_NAMESPACE
              value: "zodiac"
---
apiVersion: v1
kind: Service
metadata:
  namespace: zodiac
  name: agent-api
spec:
  type: NodePort
  selector:
    app: new-agent
  ports:
    - name: http-legacy
      protocol: TCP
      port: 3000
      targetPort: {{ .Values.agent.port }}
      nodePort: {{ .Values.agent.legacyNodePort }}
    - name: http-agent
      protocol: TCP
      port: {{ .Values.agent.port }}
      targetPort: {{ .Values.agent.port }}
      nodePort: {{ .Values.agent.nodePort }}
