apiVersion: v1
kind: ConfigMap
metadata:
  namespace: zodiac
  name: orion-ui-config
data:
  config.js: |
    window.__APP_CONFIG__ = {
      VITE_CHAT_API_BASE: "{{ .Values.orionUi.chatApiBase }}",
      VITE_CHAT_API_PATH: "{{ .Values.orionUi.chatApiPath }}",
      VITE_AGENT_API_BASE: "{{ .Values.orionUi.agentApiBase }}",
      VITE_BROKER_URL: "{{ .Values.orionUi.brokerUrl }}",
      VITE_MCP_CLIENT_URL: "{{ .Values.orionUi.clientUrl }}",
      VITE_LLM_URL: "{{ .Values.mcp.env.llmUrl }}",
    };
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zodiac
  name: orion-ui
  labels:
    app: orion-ui
  annotations:
    keel.sh/policy: minor
    keel.sh/trigger: poll

spec:
  replicas: 1
  selector:
    matchLabels:
      app: orion-ui
  template:
    metadata:
      labels:
        app: orion-ui
    spec:
      imagePullSecrets:
        - name: regcred

      volumes:
        - name: config-volume
          configMap:
            name: orion-ui-config

      containers:
        - name: orion-ui
          image: "{{ .Values.meta.imageUrl }}/orion-ui:0.2.0-cicd"

          ports:
            - containerPort: {{ .Values.orionUi.port }}

          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
---
apiVersion: v1
kind: Service
metadata:
  namespace: zodiac
  name: orion-ui
  labels:
    app: orion-ui
spec:
  type: NodePort
  selector:
    app: orion-ui
  ports:
    - name: http
      port: {{ .Values.orionUi.port }}
      targetPort: {{ .Values.orionUi.port }}
      nodePort: 30081