meta:
  imageUrl: git.tu-berlin.de:5000/zodiac/zodiac-meta
  loggingLevel: DEBUG

hivezodiac:
  serviceName: hivezodiac
  httpPort: 8080
  mqttPort: 1883
  websocketPort: 8000
  mqttNodePort: 30069

mcp:
  clientPort: 8001
  serverPort: 8000
  externalPort: 30084
  env:
    model: "gemma4:e2b"
    llmUrl: "http://elise.ise.tu-berlin.de:11434"
    mcpUrl: "http://mcp-server-service.zodiac.svc.cluster.local:32011/mcp"
    stream_manager_url: "http://stream-manager.zodiac.svc.cluster.local:8002"
    systemPrompt: "You are a Purpose-Aware MCP Bridge. Allways try to use the provided tools if applicable. Your role is to act as the intelligent interface between the user and an MQTT Broker. You translate natural language intent into precise MQTT actions using the provided tools. Alsways explain what you have done after executing an action. If you don't know how to do something, say you don't know. Do not try to fake it. The user will ask you to perform actions on the MQTT Broker, such as publishing messages or subscribing to topics. You will use the provided tools to perform these actions and provide feedback to the user."
    tokenLimit: "4096"
    otel_exporter_endpoint: "http://otel-collector.zodiac.svc.cluster.local:4318"

orionUi:
  port: 80
  chatApiBase: "http://130.149.158.32:30084"
  chatApiPath: "/chat"
  agentApiBase: "http://130.149.158.32:30086"
  clientUrl: "http://130.149.158.32:30084/health"
  brokerUrl: "http://mqtt-broker:1883"
  grafanaUrl: "http://130.149.158.133:30678/public-dashboards/645b6a3d77334d1da468182462276ded"

agent:
  port: 30086
  nodePort: 30086
  legacyNodePort: 30085
  url: "http://130.149.158.132:30086"
  mcpRequestTimeoutSeconds: "600"

logCollector:
  kubeNamespace: "zodiac"
  storageFile: "/shared/analysis_logs.jsonl"
  htmlFile: "/shared/analysis_logs.html"
  kubeLabelSelector: "app=mcp-client"

streamManager:
  port: 8002
  nodePort: 30002
  mqttBroker: "hivezodiac"
  maxTopicsPerSession: 20
  agentserverUrl: "http://agent-api:30086"

ragService:
  serviceName: "rag-service"
  port: 30110
  chromaDataDir: "/data/chroma"
  collectionPrefix: "zodiac"
  useDefaultEmbeddings: "true"
  defaultTopK: "5"
  autoIngestLocalData: "true"
  autoIngestOnlyIfEmpty: "true"
